### ISSUE TITLE
http-server as dev dependency

### ISSUE THREAD

**Issue by rugk** [nolanlawson/emoji-mart-outside-react#1]
https://github.com/nolanlawson/emoji-mart-outside-react/blob/537103519b1c957b077583c826a4d071dd0a67ff/package.json#L14

Should not this be a dev dependency only?

**Comment by rugk** [comment]
same with `webpack` actually

**Comment by nolanlawson** [comment]
This is just a demo, it doesn't really matter what's dev and what's not
