### ISSUE TITLE
Possible without webpack?

### ISSUE THREAD

**Issue by rugk** [nolanlawson/emoji-mart-outside-react#3]
Would not the same also be possible without webpack at all?
I.e. just bundle JS files from preact, remount etc. inside of the JS.

Or does webpack actually (apart from JS minification) minimize or transform the react module code or so in another way? (i.e. is there some performance impact when including it at runtime?)

**Comment by nolanlawson** [comment]
This is just a demo, I admit I don't plan on going through all the possible ways of doing this. It can definitely be done with Rollup or Parcel or whatever, but you're probably going to need a build step.
