### ISSUE TITLE
Remove prop-types

### ISSUE THREAD

**Issue by rugk** [nolanlawson/emoji-mart-outside-react#8]
Is https://github.com/missive/emoji-mart#removing-prop-types already followed here?

If not, it would likely be better to follow it to remove that lib there.

**Comment by rugk** [comment]
As we do not use babel here, however, @nolanlawson, how could we remove it?

**Comment by nolanlawson** [comment]
You would need babel, yes.

**Comment by nolanlawson** [comment]
I didn't want to overcomplicate this guide by adding production-level optimizations (e.g. that's also why I didn't do any minification), but if you want to see how to remove prop-types, please see: https://github.com/nolanlawson/pinafore/blob/861c7dbe1e51694ba59662eab52a3e4bd742077a/webpack/client.config.js#L38-L57

**Comment by rugk** [comment]
Hmm, this still uses this babel loader…
