### ISSUE TITLE
Can we drop preact-compat?

### ISSUE THREAD

**Issue by rugk** [nolanlawson/emoji-mart-outside-react#9]
AFAIK these lines:
https://github.com/nolanlawson/emoji-mart-outside-react/blob/537103519b1c957b077583c826a4d071dd0a67ff/webpack.config.js#L4-L5

...require the react compatibility module from preact to be included.

Can we maybe somehow drop this, to decrease the size?

Possibly by using a [custom adapter of remount](https://github.com/rstacruz/remount/blob/master/docs/api.md#user-content-custom-adapters).

**Comment by nolanlawson** [comment]
`preact` is the smallest React-like that I'm aware of. I don't think you could get the size down any further without implementing your own version of React specifically for emoji-mart.
